spring:
  jpa:
    hibernate:
      ddl-auto: create-drop # create, create-drop, update, validate, none
    generate-ddl: false
    show-sql: false
    defer-datasource-initialization: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #      javax:
  #        persistence:
  #          schema-generation:
  #            create-source: metadata
  #            scripts:
  #              action: create
  #              create-target: create.sql
  sql:
    init:
      mode: never
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db
    username: postgres
    password: 123456