spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: client-service
          uri: http://localhost:8082
          predicates:
            - Path=/client/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

server:
  port: 8080
