eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    instance:
      prefer-ip-address: true

  spring:
    cloud:
      config:
        override.system-properties: false