spring:
  data:
    mongodb:
      username: mongodb
      password: 123456
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
      uri: mongodb://mongodb:123456@localhost:27017/customer?authSource=admin
server:
  port: 8091