spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8091
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/auth/**

        - id: product-service
          uri: http://localhost:8092
          predicates:
            - Path=/api/v1/products/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: http://localhost:8093
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - AuthenticationFilter


server:
  port: 8080

app:
  jwtSecret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  jwtExpirationMs: 3600000000
  jwtRefreshExpirationMs: 86400000000