spring:
  jpa:
    hibernate:
      ddl-auto: create-drop # create, create-drop, update, validate, none
    generate-ddl: false
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #      javax:
  #        persistence:
  #          schema-generation:
  #            create-source: metadata
  #            scripts:
  #              action: create
  #              create-target: create.sql
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: 123456
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
          spring.json.type.mapping: orderConfirmation:dev.ecagataydogan.orderservice.kafka.OrderConfirmation

server:
  port: 8093

application:
  config:
    customer-url: http://localhost:8091/api/v1/customers
    product-url: http://localhost:8092/api/v1/products
    payment-url: http://localhost:8094/api/v1/payments
